name: itetsostituzioni
description: "Applicazione dell'Istituto Pilati per le sostituzioni dei professori."
publish_to: "none"

version: 3.0.0+7

environment:
  sdk: ">=3.2.2 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  flutter_series: ^0.1.2
  intl: ^0.18.1
  http: ^1.1.2
  flutter_riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6

flutter:
  uses-material-design: true
  assets:
    - assets/

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
  image_path_ios: assets/icon/icon_ios.png
  adaptive_icon_foreground: assets/icon/adaptive_foreground.png
  adaptive_icon_background: "#FFFFFF"

# dart run flutter_native_splash:create
flutter_native_splash:
  image: assets/splash_screen.png
  color: "#FFFFFF"
  android_12:
    color: "#FFFFFF"
    color_dark: "#222222"