name: itetsostituzioni
description: Applicazione dell&#x27;Istituto Pilati per le sostituzioni dei professori.

version: 2.0.1+6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  path_provider: ^0.5.0+1
  firebase_core: ^0.3.4
  firebase_messaging: ^4.0.0+4
  cloud_firestore: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/